using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Shouldly;
using SourceInject;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Xunit;
using Xunit.Abstractions;

namespace SourceInjectTests
{
    public class GeneratorTests
    {
        private readonly ITestOutputHelper output;

        public GeneratorTests(ITestOutputHelper output) => this.output = output ?? throw new ArgumentNullException(nameof(output));

        [Fact]
        public void GeneratedCodeWithoutServicesWork()
        {
            var source = @"
using Microsoft.Extensions.DependencyInjection;
namespace WebApp
{
    class C
    {
        void M(IServiceCollection services)
        {
            services.Discover();
        }
    }
}";
            var (attributeCode, extensionCode) = GetGeneratedOutput(source);
            attributeCode.ShouldNotBeNull();
            extensionCode.ShouldNotBeNull();

            const string expectedAttributeCode = @"// <auto-generated />
using Microsoft.Extensions.DependencyInjection;
[System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
internal class InjectAttribute : System.Attribute
{
    internal InjectAttribute(ServiceLifetime serviceLifetime = ServiceLifetime.Transient) { }
}
[System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
internal class InjectSingletonAttribute : System.Attribute
{
}
[System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
internal class InjectScopedAttribute : System.Attribute
{
}
[System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
internal class InjectTransientAttribute : System.Attribute
{
}
";
            const string expectedExtensionCode = @"// <auto-generated />
using Microsoft.Extensions.DependencyInjection;
using WebApp;

namespace WebApp
{
    public static class GeneratedServicesExtension
    {
        public static void DiscoverInFoo(this IServiceCollection services) => services.Discover();
        internal static void Discover(this IServiceCollection services)
        {
        }
    }
}

public static class FooDiscoverer
{
    public static void Discover(IServiceCollection services) => services.Discover();
}
";
            attributeCode.ShouldBe(expectedAttributeCode);
            extensionCode.ShouldBe(expectedExtensionCode);
        }

        [Fact]
        public void GeneratedCodeWithOneService()
        {
            var source = @"
using Microsoft.Extensions.DependencyInjection;

namespace WebApp
{
    class C
    {
        void M(IServiceCollection services)
        {
             services.Discover();
        }
    }
    [Inject]
    class MyService
    {
    }
}";
            var (_, extensionCode) = GetGeneratedOutput(source);
            extensionCode.ShouldNotBeNull();

            const string expectedExtensionCode = @"// <auto-generated />
using Microsoft.Extensions.DependencyInjection;
using WebApp;

namespace WebApp
{
    public static class GeneratedServicesExtension
    {
        public static void DiscoverInFoo(this IServiceCollection services) => services.Discover();
        internal static void Discover(this IServiceCollection services)
        {
            services.AddTransient<WebApp.MyService>();
        }
    }
}

public static class FooDiscoverer
{
    public static void Discover(IServiceCollection services) => services.Discover();
}
";
            extensionCode.ShouldBe(expectedExtensionCode);
        }

        [Fact]
        public void GeneratedCodeWithTwoServices()
        {
            var source = @"
using Microsoft.Extensions.DependencyInjection;

namespace WebApp
{
    class C
    {
        void M(IServiceCollection services)
        {
             services.Discover();
        }
    }
    [Inject]
    class MyService1
    {
    }
    [Inject]
    class MyService2
    {
    }
}";
            var (_, extensionCode) = GetGeneratedOutput(source);
            extensionCode.ShouldNotBeNull();

            const string expectedExtensionCode = @"// <auto-generated />
using Microsoft.Extensions.DependencyInjection;
using WebApp;

namespace WebApp
{
    public static class GeneratedServicesExtension
    {
        public static void DiscoverInFoo(this IServiceCollection services) => services.Discover();
        internal static void Discover(this IServiceCollection services)
        {
            services.AddTransient<WebApp.MyService1>();
            services.AddTransient<WebApp.MyService2>();
        }
    }
}

public static class FooDiscoverer
{
    public static void Discover(IServiceCollection services) => services.Discover();
}
";
            extensionCode.ShouldBe(expectedExtensionCode);
        }

        [Fact]
        public void GeneratedCodeWithDifferentNamespace()
        {
            var source = @"
using Microsoft.Extensions.DependencyInjection;

namespace MyNamespace
{
    class C
    {
        void M(IServiceCollection services)
        {
             services.Discover();
        }
    }
    [Inject]
    class MyService
    {
    }
}";
            var (_, extensionCode) = GetGeneratedOutput(source);
            extensionCode.ShouldNotBeNull();

            const string expectedExtensionCode = @"// <auto-generated />
using Microsoft.Extensions.DependencyInjection;
using MyNamespace;

namespace MyNamespace
{
    public static class GeneratedServicesExtension
    {
        public static void DiscoverInFoo(this IServiceCollection services) => services.Discover();
        internal static void Discover(this IServiceCollection services)
        {
            services.AddTransient<MyNamespace.MyService>();
        }
    }
}

public static class FooDiscoverer
{
    public static void Discover(IServiceCollection services) => services.Discover();
}
";
            expectedExtensionCode.ShouldBe(extensionCode);
        }

        [Fact]
        public void GeneratedCodeWithoutNamespace()
        {
            var source = @"
using Microsoft.Extensions.DependencyInjection;
class C
{
    void M(IServiceCollection services)
    {
         services.Discover();
    }
}
[Inject]
class MyService
{
}";
            var (_, extensionCode) = GetGeneratedOutput(source);
            extensionCode.ShouldNotBeNull();

            const string expectedExtensionCode = @"// <auto-generated />
using Microsoft.Extensions.DependencyInjection;

public static class GeneratedServicesExtension
{
    public static void DiscoverInFoo(this IServiceCollection services) => services.Discover();
    internal static void Discover(this IServiceCollection services)
    {
        services.AddTransient<MyService>();
    }
}

public static class FooDiscoverer
{
    public static void Discover(IServiceCollection services) => services.Discover();
}
";
            extensionCode.ShouldBe(expectedExtensionCode);
        }

        [Fact]
        public void GeneratedCodeWithTopLevelStatement()
        {
            var source = @"
using Microsoft.Extensions.DependencyInjection;
var services = new ServiceCollection();
services.Discover();
var serviceProvider = services.BuildServiceProvider();
[Inject]
class MyService
{
}";
            var (_, extensionCode) = GetGeneratedOutput(source, true);
            extensionCode.ShouldNotBeNull();

            const string expectedExtensionCode = @"// <auto-generated />
using Microsoft.Extensions.DependencyInjection;

public static class GeneratedServicesExtension
{
    public static void DiscoverInFoo(this IServiceCollection services) => services.Discover();
    internal static void Discover(this IServiceCollection services)
    {
        services.AddTransient<MyService>();
    }
}

public static class FooDiscoverer
{
    public static void Discover(IServiceCollection services) => services.Discover();
}
";
            extensionCode.ShouldBe(expectedExtensionCode);
        }

        [Fact]
        public void GeneratedScoped()
        {
            var source = @"
using Microsoft.Extensions.DependencyInjection;
class C
{
    void M(IServiceCollection services)
    {
         services.Discover();
    }
}
[Inject(ServiceLifetime.Scoped)]
class MyService
{
}";
            var (_, extensionCode) = GetGeneratedOutput(source);
            extensionCode.ShouldNotBeNull();

            const string expectedExtensionCode = @"// <auto-generated />
using Microsoft.Extensions.DependencyInjection;

public static class GeneratedServicesExtension
{
    public static void DiscoverInFoo(this IServiceCollection services) => services.Discover();
    internal static void Discover(this IServiceCollection services)
    {
        services.AddScoped<MyService>();
    }
}

public static class FooDiscoverer
{
    public static void Discover(IServiceCollection services) => services.Discover();
}
";
            extensionCode.ShouldBe(expectedExtensionCode);
        }

        [Fact]
        public void GeneratedScopedWithSpecificMethod()
        {
            var source = @"
using Microsoft.Extensions.DependencyInjection;
class C
{
    void M(IServiceCollection services)
    {
         services.Discover();
    }
}
[InjectScoped]
class MyService
{
}";
            var (_, extensionCode) = GetGeneratedOutput(source);
            extensionCode.ShouldNotBeNull();

            const string expectedExtensionCode = @"// <auto-generated />
using Microsoft.Extensions.DependencyInjection;

public static class GeneratedServicesExtension
{
    public static void DiscoverInFoo(this IServiceCollection services) => services.Discover();
    internal static void Discover(this IServiceCollection services)
    {
        services.AddScoped<MyService>();
    }
}

public static class FooDiscoverer
{
    public static void Discover(IServiceCollection services) => services.Discover();
}
";
            extensionCode.ShouldBe(expectedExtensionCode);
        }

        [Fact]
        public void GeneratedTransient()
        {
            var source = @"
using Microsoft.Extensions.DependencyInjection;
class C
{
    void M(IServiceCollection services)
    {
         services.Discover();
    }
}
[Inject(ServiceLifetime.Transient)]
class MyService
{
}";
            var (_, extensionCode) = GetGeneratedOutput(source);
            extensionCode.ShouldNotBeNull();

            const string expectedExtensionCode = @"// <auto-generated />
using Microsoft.Extensions.DependencyInjection;

public static class GeneratedServicesExtension
{
    public static void DiscoverInFoo(this IServiceCollection services) => services.Discover();
    internal static void Discover(this IServiceCollection services)
    {
        services.AddTransient<MyService>();
    }
}

public static class FooDiscoverer
{
    public static void Discover(IServiceCollection services) => services.Discover();
}
";
            extensionCode.ShouldBe(expectedExtensionCode);
        }

        [Fact]
        public void GeneratedTransientWithSpecificMethod()
        {
            var source = @"
using Microsoft.Extensions.DependencyInjection;
class C
{
    void M(IServiceCollection services)
    {
         services.Discover();
    }
}
[InjectTransient]
class MyService
{
}";
            var (_, extensionCode) = GetGeneratedOutput(source);
            extensionCode.ShouldNotBeNull();

            const string expectedExtensionCode = @"// <auto-generated />
using Microsoft.Extensions.DependencyInjection;

public static class GeneratedServicesExtension
{
    public static void DiscoverInFoo(this IServiceCollection services) => services.Discover();
    internal static void Discover(this IServiceCollection services)
    {
        services.AddTransient<MyService>();
    }
}

public static class FooDiscoverer
{
    public static void Discover(IServiceCollection services) => services.Discover();
}
";
            extensionCode.ShouldBe(expectedExtensionCode);
        }

        [Fact]
        public void GeneratedSingleton()
        {
            var source = @"
using Microsoft.Extensions.DependencyInjection;
class C
{
    void M(IServiceCollection services)
    {
         services.Discover();
    }
}
[Inject(ServiceLifetime.Singleton)]
class MyService
{
}";
            var (_, extensionCode) = GetGeneratedOutput(source);
            extensionCode.ShouldNotBeNull();

            const string expectedExtensionCode = @"// <auto-generated />
using Microsoft.Extensions.DependencyInjection;

public static class GeneratedServicesExtension
{
    public static void DiscoverInFoo(this IServiceCollection services) => services.Discover();
    internal static void Discover(this IServiceCollection services)
    {
        services.AddSingleton<MyService>();
    }
}

public static class FooDiscoverer
{
    public static void Discover(IServiceCollection services) => services.Discover();
}
";
            extensionCode.ShouldBe(expectedExtensionCode);
        }

        [Fact]
        public void GeneratedSingletonWithSpecificMethod()
        {
            var source = @"
using Microsoft.Extensions.DependencyInjection;
class C
{
    void M(IServiceCollection services)
    {
         services.Discover();
    }
}
[InjectSingleton]
class MyService
{
}";
            var (_, extensionCode) = GetGeneratedOutput(source);
            extensionCode.ShouldNotBeNull();

            const string expectedExtensionCode = @"// <auto-generated />
using Microsoft.Extensions.DependencyInjection;

public static class GeneratedServicesExtension
{
    public static void DiscoverInFoo(this IServiceCollection services) => services.Discover();
    internal static void Discover(this IServiceCollection services)
    {
        services.AddSingleton<MyService>();
    }
}

public static class FooDiscoverer
{
    public static void Discover(IServiceCollection services) => services.Discover();
}
";
            extensionCode.ShouldBe(expectedExtensionCode);
        }

        private (string, string) GetGeneratedOutput(string source, bool executable = false)
        {
            var outputCompilation = CreateCompilation(source, executable);
            var trees = outputCompilation.SyntaxTrees.Reverse().Take(2).Reverse().ToList();
            foreach (var tree in trees)
            {
                output.WriteLine(Path.GetFileName(tree.FilePath) + ":");
                output.WriteLine(tree.ToString());
            }
            return (trees.First().ToString(), trees[1].ToString());
        }

        private static Compilation CreateCompilation(string source, bool executable)
        {
            var syntaxTree = CSharpSyntaxTree.ParseText(source);

            var references = new List<MetadataReference>();
            foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
                if (!assembly.IsDynamic && !string.IsNullOrWhiteSpace(assembly.Location))
                    references.Add(MetadataReference.CreateFromFile(assembly.Location));

            var compilation = CSharpCompilation.Create("Foo",
                                                       new SyntaxTree[] { syntaxTree },
                                                       references,
                                                       new CSharpCompilationOptions(executable ? OutputKind.ConsoleApplication : OutputKind.DynamicallyLinkedLibrary));

            var generator = new Generator();

            var driver = CSharpGeneratorDriver.Create(generator);
            driver.RunGeneratorsAndUpdateCompilation(compilation, out var outputCompilation, out var generateDiagnostics);

            var compileDiagnostics = outputCompilation.GetDiagnostics();
            compileDiagnostics.Any(d => d.Severity == DiagnosticSeverity.Error).ShouldBeFalse("Failed: " + compileDiagnostics.FirstOrDefault()?.GetMessage());

            generateDiagnostics.Any(d => d.Severity == DiagnosticSeverity.Error).ShouldBeFalse("Failed: " + generateDiagnostics.FirstOrDefault()?.GetMessage());
            return outputCompilation;
        }
    }
}
